<a href="https://colab.research.google.com/github/hena1019/GTU-FINAL-YEAR-COMPUTER-SCIENCE-PYTHON-PRACTICALS/blob/main/PRAC3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def removeduplicate(A):
   newlist = []
   for n in A:
      if n not in newlist:
         newlist.append(n)
   return newlist
A=list()
n=int(input("Enter the size of the List ::"))
print("Enter the number ::")
for i in range(int(n)):
   k=int(input(""))
   A.append(int(k))
print("THE NEW LIST IS ::>",removeduplicate(A))

Enter the size of the List ::6
Enter the number ::
1
2
21
21
1
21
THE NEW LIST IS ::> [1, 2, 21]


In [ ]:
def frequency_of_items_in_list(l): 
    d={} 
    for i in l: 
        c=l.count(i) 
        d[i]=c 
    return d 
 
n=int(input("Enter the size of your desired list: ")) 
l=[]
print("Enter the number :") 
for i in range(n): 
    x=int(input("")) 
    l.append(x) 
print("\nThe list entered by the user is",l) 
print() 
s=frequency_of_items_in_list(l) 
for k,v in s.items(): 
    print(k," appeared ",v,"times") 


Enter the size of your desired list: 8
Enter the number :
1
6
8
8
8
6
1
1

The list entered by the user is [1, 6, 8, 8, 8, 6, 1, 1]

1  appeared  3 times
6  appeared  2 times
8  appeared  3 times


In [ ]:
NumList = []

Number = int(input("Please enter the Total Number of List Elements: "))
print("Enter the number :")
for i in range(1, Number + 1):
    value = int(input(""))
    NumList.append(value)

for i in range (Number):
    for j in range(i + 1, Number):
        if(NumList[i] > NumList[j]):
            temp = NumList[i]
            NumList[i] = NumList[j]
            NumList[j] = temp

print("Element After Sorting List in Ascending Order is : ", NumList)

Please enter the Total Number of List Elements: 9
Enter the number :
23
45
36
27
98
12
56
78
85
Element After Sorting List in Ascending Order is :  [12, 23, 27, 36, 45, 56, 78, 85, 98]


In [ ]:
import numpy as np 
print("Enter values of matrix 1")
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
print("Enter the entries in a single line (separated by space): ") 
# User input of entries in a 
# single line separated by space 
entries = list(map(int, input().split())) 
# For printing the matrix 
X = np.array(entries).reshape(R, C) 
print(X) 

print("\nEnter values of matrix 2")
A = int(input("Enter the number of rows:")) 
B = int(input("Enter the number of columns:")) 
print("Enter the entries in a single line (separated by space): ") 
# User input of entries in a 
# single line separated by space 
entries = list(map(int, input().split())) 
# For printing the matrix 
Y = np.array(entries).reshape(A, B) 
print(Y)

#MATRIX ADDITION
result = [[X[i][j] + Y[i][j] for j in range
(len(X[0]))] for i in range(len(X))]
print("\nMATRIX ADDITION") 
for r in result: 
	print(r)

#MATRIX MULTIPLICATION
print("\n MATRIX MULTIPLICATION")
res = np.dot(X,Y)
print(res)

Enter values of matrix 1
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]

Enter values of matrix 2
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]

MATRIX ADDITION
[
[2, 4]
[6, 8]
]

 MATRIX MULTIPLICATION
[[ 7 10]
 [15 22]]


In [ ]:
n=int(input("Enter number of rows: "))
a=[]
for i in range(n):
    a.append([])
    a[i].append(1)
    for j in range(1,i):
        a[i].append(a[i-1][j-1]+a[i-1][j])
    if(n!=0):
        a[i].append(1)
for i in range(n):
    print("   "*(n-i),end=" ",sep=" ")
    for j in range(0,i+1):
        print('{0:6}'.format(a[i][j]),end=" ",sep=" ")
    print()

Enter number of rows: 5
                     1 
                  1      1 
               1      2      1 
            1      3      3      1 
         1      4      6      4      1 


In [ ]:
tpl = (1,2,3,4,5,6,7,8,9,10)
tpl1 = tuple(filter(lambda x : x%2==0,tpl))  
print(tpl1)

(2, 4, 6, 8, 10)


In [ ]:
# creating an empty list
lst = []
# number of elemetns as input
n = int(input("Enter number of elements : "))
# iterating till the range
for i in range(0, n):
  ele = (input())
  lst.append(ele) # adding the element
  tupl=tuple(lst) #converting list into tuple
print(tupl) #print tuple

a = int(input("Enter the place of the element you want to remove : "))
tupl = tupl[ : a ] + tupl[a+1 : ]
print(tupl)

Enter number of elements : 5
1
2
3
abcdgjj
4
('1', '2', '3', 'abcdgjj', '4')
Enter the place of the element you want to remove : 3
('1', '2', '3', '4')
